module.exports = {
    "en_US": "MMMM d, y 'at' h:mm:ss a z",
    "en_GB": "d MMMM y 'at' HH:mm:ss z",
    "en_CA": "MMMM d, y 'at' h:mm:ss a z",
    "da_DK": "d. MMMM y 'kl'. HH.mm.ss z",
    "de_AT": "d. MMMM y 'um' HH:mm:ss z",
    "de_CH": "d. MMMM y 'um' HH:mm:ss z",
    "de_DE": "d. MMMM y 'um' HH:mm:ss z",
    "de_LU": "d. MMMM y 'um' HH:mm:ss z",
    "el_GR": "d MMMM y - h:mm:ss a z",
    "en_IE": "d MMMM y 'at' HH:mm:ss z",
    "es_ES": "d 'de' MMMM 'de' y, H:mm:ss z",
    "fi_FI": "d. MMMM y 'klo' H.mm.ss z",
    "fr_BE": "d MMMM y 'à' HH:mm:ss z",
    "fr_CA": "d MMMM y 'à' HH:mm:ss z",
    "fr_CH": "d MMMM y 'à' HH:mm:ss z",
    "fr_FR": "d MMMM y 'à' HH:mm:ss z",
    "fr_LU": "d MMMM y 'à' HH:mm:ss z",
    "it_CH": "d MMMM y HH:mm:ss z",
    "it_IT": "d MMMM y HH:mm:ss z",
    "ja_JP": "y年M月d日 H:mm:ss z",
    "zh_CN": "y年M月d日 z ah:mm:ss",
    "nl_BE": "d MMMM y 'om' HH:mm:ss z",
    "nl_NL": "d MMMM y 'om' HH:mm:ss z",
    "no_NO": "d. MMMM y 'kl'. HH:mm:ss z",
    "pt_PT": "d 'de' MMMM 'de' y 'às' HH:mm:ss z",
    "sv_SE": "d MMMM y HH:mm:ss z",
    "zh_TW": "y年M月d日 ah:mm:ss [z]",
    "ar": "d MMMM، y h:mm:ss a z",
    "ca": "d MMMM 'de' y 'a' 'les' H:mm:ss z",
    "ca_ES": "d MMMM 'de' y 'a' 'les' H:mm:ss z",
    "ca_ES_EURO": "d MMMM 'de' y 'a' 'les' H:mm:ss z",
    "cs_CZ": "d. MMMM y H:mm:ss z",
    "de": "d. MMMM y 'um' HH:mm:ss z",
    "de_AT_EURO": "d. MMMM y 'um' HH:mm:ss z",
    "de_DE_EURO": "d. MMMM y 'um' HH:mm:ss z",
    "de_LU_EURO": "d. MMMM y 'um' HH:mm:ss z",
    "en_AU": "d MMMM y 'at' h:mm:ss a z",
    "en_IE_EURO": "d MMMM y 'at' HH:mm:ss z",
    "en_NZ": "d MMMM y 'at' h:mm:ss a z",
    "en_ZA": "dd MMMM y 'at' HH:mm:ss z",
    "es": "d 'de' MMMM 'de' y, H:mm:ss z",
    "es_AR": "d 'de' MMMM 'de' y, HH:mm:ss z",
    "es_CO": "d 'de' MMMM 'de' y, h:mm:ss a z",
    "es_ES_EURO": "d 'de' MMMM 'de' y, H:mm:ss z",
    "es_MX": "d 'de' MMMM 'de' y, HH:mm:ss z",
    "es_VE": "d 'de' MMMM 'de' y, h:mm:ss a z",
    "fi_FI_EURO": "d. MMMM y 'klo' H.mm.ss z",
    "fr": "d MMMM y 'à' HH:mm:ss z",
    "fr_FR_EURO": "d MMMM y 'à' HH:mm:ss z",
    "it": "d MMMM y HH:mm:ss z",
    "iw": "d בMMMM y בשעה H:mm:ss z",
    "ja": "y年M月d日 H:mm:ss z",
    "ko": "y년 M월 d일 a h시 m분 s초 z",
    "no": "d. MMMM y 'kl'. HH:mm:ss z",
    "pl": "d MMMM y HH:mm:ss z",
    "pt": "d 'de' MMMM 'de' y HH:mm:ss z",
    "ru": "d MMMM y 'г'., H:mm:ss z",
    "sv": "d MMMM y HH:mm:ss z",
    "th": "d MMMM y H นาฬิกา mm นาที ss วินาที z",
    "tr": "d MMMM y HH:mm:ss z",
    "zh": "y年M月d日 z ah:mm:ss",
    "zh_HK": "y年M月d日 ah:mm:ss [z]",
    "ko_KR": "y년 M월 d일 a h시 m분 s초 z",
    "pt_BR": "d 'de' MMMM 'de' y HH:mm:ss z",
    "hu": "y. MMMM d. H:mm:ss z",
    "fi": "d. MMMM y 'klo' H.mm.ss z",
    "nl": "d MMMM y 'om' HH:mm:ss z",
    "th_TH": "d MMMM y H นาฬิกา mm นาที ss วินาที z",
    "cs": "d. MMMM y H:mm:ss z",
    "da": "d. MMMM y 'kl'. HH.mm.ss z",
    "ar_AE": "d MMMM، y h:mm:ss a z",
    "ar_BH": "d MMMM، y h:mm:ss a z",
    "ar_JO": "d MMMM، y h:mm:ss a z",
    "ar_KW": "d MMMM، y h:mm:ss a z",
    "ar_LB": "d MMMM، y h:mm:ss a z",
    "ar_SA": "d MMMM، y G h:mm:ss a z",
    "bg_BG": "d MMMM y 'г'., H:mm:ss z",
    "en_BB": "d MMMM y 'at' h:mm:ss a z",
    "en_BM": "d MMMM y 'at' h:mm:ss a z",
    "en_GH": "d MMMM y 'at' h:mm:ss a z",
    "en_ID": "MMMM d, y 'at' h:mm:ss a z",
    "en_SG": "d MMMM y 'at' h:mm:ss a z",
    "es_BO": "d 'de' MMMM 'de' y, HH:mm:ss z",
    "es_CL": "d 'de' MMMM 'de' y, HH:mm:ss z",
    "es_CR": "d 'de' MMMM 'de' y, HH:mm:ss z",
    "es_EC": "d 'de' MMMM 'de' y, HH:mm:ss z",
    "es_GT": "d 'de' MMMM 'de' y, HH:mm:ss z",
    "es_HN": "dd 'de' MMMM 'de' y, HH:mm:ss z",
    "es_PE": "d 'de' MMMM 'de' y, HH:mm:ss z",
    "es_PR": "d 'de' MMMM 'de' y, h:mm:ss a z",
    "es_PY": "d 'de' MMMM 'de' y, HH:mm:ss z",
    "es_SV": "d 'de' MMMM 'de' y, HH:mm:ss z",
    "es_UY": "d 'de' MMMM 'de' y, HH:mm:ss z",
    "et_EE": "d. MMMM y HH:mm:ss z",
    "fr_MC": "d MMMM y 'à' HH:mm:ss z",
    "hr_HR": "d. MMMM y. 'u' HH:mm:ss z",
    "hy_AM": "dd MMMM, y թ., HH:mm:ss z",
    "is_IS": "d. MMMM y 'kl'. HH:mm:ss z",
    "iw_IL": "d בMMMM y בשעה H:mm:ss z",
    "kk_KZ": "y 'ж'. d MMMM, HH:mm:ss z",
    "km_KH": "d MMMM y នៅ​ម៉ោង h:mm:ss a z",
    "lt_LT": "y 'm'. MMMM d 'd'. HH:mm:ss z",
    "lv_LV": "y. 'gada' d. MMMM HH:mm:ss z",
    "ms_MY": "d MMMM y h:mm:ss a z",
    "nl_SR": "d MMMM y 'om' HH:mm:ss z",
    "pt_AO": "d 'de' MMMM 'de' y 'às' HH:mm:ss z",
    "ro_RO": "d MMMM y, HH:mm:ss z",
    "sk_SK": "d. MMMM y, H:mm:ss z",
    "sl_SI": "dd. MMMM y HH:mm:ss z",
    "ur_PK": "d MMMM، y h:mm:ss a z",
    "vi_VN": "HH:mm:ss z d MMMM, y",
    "in": "d MMMM y HH.mm.ss z",
    "ro": "d MMMM y, HH:mm:ss z",
    "vi": "HH:mm:ss z d MMMM, y",
    "uk": "d MMMM y 'р'. 'о' HH:mm:ss z",
    "uk_UA": "d MMMM y 'р'. 'о' HH:mm:ss z",
    "ru_RU": "d MMMM y 'г'., H:mm:ss z",
    "el": "d MMMM y - h:mm:ss a z",
    "bg": "d MMMM y 'г'., H:mm:ss z",
    "es_DO": "d 'de' MMMM 'de' y, h:mm:ss a z",
    "en_NG": "d MMMM y 'at' h:mm:ss a z",
    "ar_EG": "d MMMM، y h:mm:ss a z",
    "es_PA": "d 'de' MMMM 'de' y, h:mm:ss a z",
    "en_PH": "d MMMM y 'at' h:mm:ss a z",
    "tl": "MMMM d, y 'nang' h:mm:ss a z",
    "tl_PH": "MMMM d, y 'nang' h:mm:ss a z",
    "en_IN": "d MMMM y 'at' h:mm:ss a z",
    "ka": "d MMMM, y, HH:mm:ss z",
    "ka_GE": "d MMMM, y, HH:mm:ss z",
    "sr": "dd. MMMM y. HH:mm:ss z",
    "sr_CS": "dd. MMMM y. HH:mm:ss z",
    "sr_BA": "dd. MMMM y. HH:mm:ss z",
    "sk": "d. MMMM y, H:mm:ss z",
    "en_MY": "d MMMM y 'at' h:mm:ss a z",
    "sh": "dd. MMMM y. HH:mm:ss z",
    "sh_CS": "dd. MMMM y. HH:mm:ss z",
    "sh_BA": "dd. MMMM y. HH:mm:ss z",
    "bs": "d. MMMM y. 'u' HH:mm:ss z",
    "bs_BA": "d. MMMM y. 'u' HH:mm:ss z",
    "hr": "d. MMMM y. 'u' HH:mm:ss z",
    "sl": "dd. MMMM y HH:mm:ss z",
    "ro_MD": "d MMMM y, HH:mm:ss z",
    "mk": "dd MMMM y HH:mm:ss z",
    "mk_MK": "dd MMMM y HH:mm:ss z",
    "et": "d. MMMM y HH:mm:ss z",
    "lv": "y. 'gada' d. MMMM HH:mm:ss z",
    "lt": "y 'm'. MMMM d 'd'. HH:mm:ss z",
    "sq": "d MMMM y 'në' h:mm:ss a, z",
    "sq_AL": "d MMMM y 'në' h:mm:ss a, z",
    "eu": "y('e')'ko' MMMM d HH:mm:ss (z)",
    "eu_ES": "y('e')'ko' MMMM d HH:mm:ss (z)",
    "mt": "d 'ta'’ MMMM y HH:mm:ss z",
    "mt_MT": "d 'ta'’ MMMM y HH:mm:ss z",
    "ga": "d MMMM y HH:mm:ss z",
    "ga_IE": "d MMMM y HH:mm:ss z",
    "sh_ME": "dd. MMMM y. HH:mm:ss z",
    "is": "d. MMMM y 'kl'. HH:mm:ss z",
    "cy": "d MMMM y 'am' HH:mm:ss z",
    "cy_GB": "d MMMM y 'am' HH:mm:ss z",
    "az_AZ": "d MMMM y HH:mm:ss z",
    "ky_KG": "y-'ж'., d-MMMM HH:mm:ss z",
    "hi_IN": "d MMMM y को h:mm:ss a z",
    "en_PK": "d MMMM y 'at' h:mm:ss a z",
    "bn_BD": "d MMMM, y h:mm:ss a z",
    "ar_QA": "d MMMM، y h:mm:ss a z",
    "be_BY": "d MMMM y 'г'. 'у' HH:mm:ss z",
    "tg_TJ": "MMMM d, y 'at' h:mm:ss a z",
    "ms": "d MMMM y h:mm:ss a z",
    "ms_BN": "d MMMM y h:mm:ss a z",
    "zh_MO": "y年M月d日 ah:mm:ss [z]",
    "zh_SG": "y年M月d日 z ah:mm:ss",
    "hy": "dd MMMM, y թ., HH:mm:ss z",
    "hi": "d MMMM y को h:mm:ss a z",
    "rm": "d 'da' MMMM y HH:mm:ss z",
    "rm_CH": "d 'da' MMMM y HH:mm:ss z",
    "lb": "d. MMMM y HH:mm:ss z",
    "lb_LU": "d. MMMM y HH:mm:ss z",
    "ur": "d MMMM، y h:mm:ss a z",
    "pl_PL": "d MMMM y HH:mm:ss z",
    "hu_HU": "y. MMMM d. H:mm:ss z",
    "in_ID": "d MMMM y HH.mm.ss z",
    "tr_TR": "d MMMM y HH:mm:ss z",
    "zh_CN_STROKE": "y年M月d日 z ah:mm:ss",
    "zh_TW_STROKE": "y年M月d日 ah:mm:ss [z]",
    "zh_HK_STROKE": "y年M月d日 ah:mm:ss [z]",
    "zh_CN_PINYIN": "y年M月d日 z ah:mm:ss",
    "bn": "d MMMM, y h:mm:ss a z",
    "ta": "d MMMM, y ’அன்று’ a h:mm:ss z",
    "ta_IN": "d MMMM, y ’அன்று’ a h:mm:ss z",
    "ar_DZ": "d MMMM، y h:mm:ss a z",
    "ar_IQ": "d MMMM، y h:mm:ss a z",
    "ar_LY": "d MMMM، y h:mm:ss a z",
    "ar_MA": "d MMMM، y HH:mm:ss z",
    "ar_OM": "d MMMM، y h:mm:ss a z",
    "ar_SD": "d MMMM، y h:mm:ss a z",
    "ar_SY": "d MMMM، y h:mm:ss a z",
    "ar_TN": "d MMMM، y h:mm:ss a z",
    "ar_YE": "d MMMM، y h:mm:ss a z",
    "en_HK": "d MMMM y 'at' h:mm:ss a z",
    "es_NI": "d 'de' MMMM 'de' y, HH:mm:ss z",
    "es_US": "d 'de' MMMM 'de' y, h:mm:ss a z",
    "eo": "y-MMMM-dd HH:mm:ss z",
    "eo_US": "y-MMMM-dd HH:mm:ss z",
    "iw_EO": "d בMMMM y בשעה H:mm:ss z",
    "en_UG": "d MMMM y 'at' HH:mm:ss z",
    "en_KY": "d MMMM y 'at' h:mm:ss a z",
    "en_TT": "d MMMM y 'at' h:mm:ss a z",
    "ta_LK": "d MMMM, y ’அன்று’ HH:mm:ss z",
    "en_SH": "d MMMM y 'at' HH:mm:ss z",
    "so_DJ": "dd MMMM y h:mm:ss a z",
    "dz_BT": "སྤྱི་ལོ་y MMMM ཚེས་ dd ཆུ་ཚོད་ h སྐར་མ་ mm:ss a z",
    "fr_HT": "d MMMM y 'à' HH:mm:ss z",
    "en_SX": "d MMMM y 'at' HH:mm:ss z",
    "en_SL": "d MMMM y 'at' h:mm:ss a z",
    "en_SC": "d MMMM y 'at' HH:mm:ss z",
    "en_FK": "d MMMM y 'at' HH:mm:ss z",
    "en_MW": "d MMMM y 'at' h:mm:ss a z",
    "en_ER": "d MMMM y 'at' h:mm:ss a z",
    "en_PG": "d MMMM y 'at' h:mm:ss a z",
    "en_AG": "d MMMM y 'at' h:mm:ss a z",
    "en_GI": "d MMMM y 'at' HH:mm:ss z",
    "en_RW": "d MMMM y 'at' HH:mm:ss z",
    "fa_IR": "d MMMM y، ساعت H:mm:ss (z)",
    "en_BW": "dd MMMM y 'at' HH:mm:ss z",
    "en_BS": "d MMMM y 'at' h:mm:ss a z",
    "en_VU": "d MMMM y 'at' h:mm:ss a z",
    "ti_ET": "dd MMMM y h:mm:ss a z",
    "en_FJ": "d MMMM y 'at' h:mm:ss a z",
    "pt_ST": "d 'de' MMMM 'de' y 'às' HH:mm:ss z",
    "fr_WF": "d MMMM y 'à' HH:mm:ss z",
    "en_JM": "d MMMM y 'at' h:mm:ss a z",
    "en_MG": "d MMMM y 'at' HH:mm:ss z",
    "fr_MR": "d MMMM y 'à' h:mm:ss a z",
    "en_WS": "d MMMM y 'at' h:mm:ss a z",
    "rn_BI": "d MMMM y HH:mm:ss z",
    "fr_KM": "d MMMM y 'à' HH:mm:ss z",
    "fr_GN": "d MMMM y 'à' HH:mm:ss z",
    "en_SB": "d MMMM y 'at' h:mm:ss a z",
    "my_MM": "d MMMM y z HH:mm:ss",
    "pt_CV": "d 'de' MMMM 'de' y 'às' HH:mm:ss z",
    "en_KE": "d MMMM y 'at' HH:mm:ss z",
    "nl_AW": "d MMMM y 'om' HH:mm:ss z",
    "pt_MZ": "d 'de' MMMM 'de' y 'às' HH:mm:ss z",
    "yo_BJ": "d MMMM y HH:mm:ss z",
    "en_LR": "d MMMM y 'at' h:mm:ss a z",
    "en_MU": "d MMMM y 'at' HH:mm:ss z",
    "en_BZ": "dd MMMM y 'at' HH:mm:ss z",
    "lu_CD": "d MMMM y HH:mm:ss z",
    "es_CU": "d 'de' MMMM 'de' y, HH:mm:ss z",
    "en_GM": "d MMMM y 'at' h:mm:ss a z",
    "en_CM": "d MMMM y 'at' HH:mm:ss z",
    "uz_LATN_UZ": "d-MMMM, y, H:mm:ss (z)",
    "en_GY": "d MMMM y 'at' h:mm:ss a z",
    "ps_AF": "د G y د MMMM d H:mm:ss (z)",
    "ne_NP": "y MMMM d HH:mm:ss z",
    "en_NA": "d MMMM y 'at' h:mm:ss a z",
    "so_SO": "dd MMMM y h:mm:ss a z",
    "lo_LA": "d MMMM y, H ໂມງ m ນາທີ ss ວິນາທີ z",
    "en_SZ": "d MMMM y 'at' h:mm:ss a z",
    "en_TO": "d MMMM y 'at' h:mm:ss a z",
    "en_TZ": "d MMMM y 'at' HH:mm:ss z",
    "ko_KP": "y년 M월 d일 a h시 m분 s초 z",
    "sr_RS": "dd. MMMM y. HH:mm:ss z",
    "de_BE": "d. MMMM y 'um' HH:mm:ss z",
};