module.exports = {
    "en_US": "M/d/yy, h:mm a",
    "en_GB": "dd/MM/y, HH:mm",
    "en_CA": "y-MM-dd, h:mm a",
    "da_DK": "dd/MM/y HH.mm",
    "de_AT": "dd.MM.yy, HH:mm",
    "de_CH": "dd.MM.yy, HH:mm",
    "de_DE": "dd.MM.yy, HH:mm",
    "de_LU": "dd.MM.yy, HH:mm",
    "el_GR": "d/M/yy, h:mm a",
    "en_IE": "dd/MM/y, HH:mm",
    "es_ES": "d/M/yy H:mm",
    "fi_FI": "d.M.y H.mm",
    "fr_BE": "d/MM/yy HH:mm",
    "fr_CA": "yy-MM-dd HH 'h' mm",
    "fr_CH": "dd.MM.yy HH:mm",
    "fr_FR": "dd/MM/y HH:mm",
    "fr_LU": "dd/MM/y HH:mm",
    "it_CH": "dd.MM.yy, HH:mm",
    "it_IT": "dd/MM/yy, HH:mm",
    "ja_JP": "y/MM/dd H:mm",
    "zh_CN": "y/M/d ah:mm",
    "nl_BE": "d/MM/yy HH:mm",
    "nl_NL": "dd-MM-yy HH:mm",
    "no_NO": "dd.MM.y, HH:mm",
    "pt_PT": "dd/MM/yy, HH:mm",
    "sv_SE": "y-MM-dd HH:mm",
    "zh_TW": "y/M/d ah:mm",
    "ar": "d‏/M‏/y h:mm a",
    "ca": "d/M/yy H:mm",
    "ca_ES": "d/M/yy H:mm",
    "ca_ES_EURO": "d/M/yy H:mm",
    "cs_CZ": "dd.MM.yy H:mm",
    "de": "dd.MM.yy, HH:mm",
    "de_AT_EURO": "dd.MM.yy, HH:mm",
    "de_DE_EURO": "dd.MM.yy, HH:mm",
    "de_LU_EURO": "dd.MM.yy, HH:mm",
    "en_AU": "d/M/yy, h:mm a",
    "en_IE_EURO": "dd/MM/y, HH:mm",
    "en_NZ": "d/MM/yy, h:mm a",
    "en_ZA": "y/MM/dd, HH:mm",
    "es": "d/M/yy H:mm",
    "es_AR": "d/M/yy HH:mm",
    "es_CO": "d/MM/yy, h:mm a",
    "es_ES_EURO": "d/M/yy H:mm",
    "es_MX": "dd/MM/yy HH:mm",
    "es_VE": "d/M/yy h:mm a",
    "fi_FI_EURO": "d.M.y H.mm",
    "fr": "dd/MM/y HH:mm",
    "fr_FR_EURO": "dd/MM/y HH:mm",
    "it": "dd/MM/yy, HH:mm",
    "iw": "d.M.y, H:mm",
    "ja": "y/MM/dd H:mm",
    "ko": "yy. M. d. a h:mm",
    "no": "dd.MM.y, HH:mm",
    "pl": "dd.MM.y, HH:mm",
    "pt": "dd/MM/y HH:mm",
    "ru": "dd.MM.y, H:mm",
    "sv": "y-MM-dd HH:mm",
    "th": "d/M/yy HH:mm",
    "tr": "d.MM.y HH:mm",
    "zh": "y/M/d ah:mm",
    "zh_HK": "d/M/y ah:mm",
    "ko_KR": "yy. M. d. a h:mm",
    "pt_BR": "dd/MM/y HH:mm",
    "hu": "y. MM. dd. H:mm",
    "fi": "d.M.y H.mm",
    "nl": "dd-MM-yy HH:mm",
    "th_TH": "d/M/yy HH:mm",
    "cs": "dd.MM.yy H:mm",
    "da": "dd/MM/y HH.mm",
    "ar_AE": "d‏/M‏/y h:mm a",
    "ar_BH": "d‏/M‏/y h:mm a",
    "ar_JO": "d‏/M‏/y h:mm a",
    "ar_KW": "d‏/M‏/y h:mm a",
    "ar_LB": "d‏/M‏/y h:mm a",
    "ar_SA": "d‏/M‏/y GGGGG h:mm a",
    "bg_BG": "d.MM.yy 'г'., H:mm",
    "en_BB": "dd/MM/y, h:mm a",
    "en_BM": "dd/MM/y, h:mm a",
    "en_GH": "dd/MM/y, h:mm a",
    "en_ID": "M/d/yy, h:mm a",
    "en_SG": "d/M/yy, h:mm a",
    "es_BO": "d/M/yy HH:mm",
    "es_CL": "dd-MM-yy HH:mm",
    "es_CR": "d/M/yy HH:mm",
    "es_EC": "d/M/yy HH:mm",
    "es_GT": "d/MM/yy HH:mm",
    "es_HN": "d/M/yy HH:mm",
    "es_PE": "d/MM/yy HH:mm",
    "es_PR": "MM/dd/yy h:mm a",
    "es_PY": "d/M/yy HH:mm",
    "es_SV": "d/M/yy HH:mm",
    "es_UY": "d/M/yy HH:mm",
    "et_EE": "dd.MM.yy HH:mm",
    "fr_MC": "dd/MM/y HH:mm",
    "hr_HR": "dd. MM. y. HH:mm",
    "hy_AM": "dd.MM.yy, HH:mm",
    "is_IS": "d.M.y, HH:mm",
    "iw_IL": "d.M.y, H:mm",
    "kk_KZ": "dd.MM.yy, HH:mm",
    "km_KH": "d/M/yy, h:mm a",
    "lt_LT": "y-MM-dd HH:mm",
    "lv_LV": "dd.MM.yy HH:mm",
    "ms_MY": "d/MM/yy h:mm a",
    "nl_SR": "dd-MM-yy HH:mm",
    "pt_AO": "dd/MM/yy, HH:mm",
    "ro_RO": "dd.MM.y, HH:mm",
    "sk_SK": "d. M. y H:mm",
    "sl_SI": "d. MM. yy HH:mm",
    "ur_PK": "d/M/yy h:mm a",
    "vi_VN": "HH:mm, dd/MM/y",
    "in": "dd/MM/yy HH.mm",
    "ro": "dd.MM.y, HH:mm",
    "vi": "HH:mm, dd/MM/y",
    "uk": "dd.MM.yy, HH:mm",
    "uk_UA": "dd.MM.yy, HH:mm",
    "ru_RU": "dd.MM.y, H:mm",
    "el": "d/M/yy, h:mm a",
    "bg": "d.MM.yy 'г'., H:mm",
    "es_DO": "d/M/yy h:mm a",
    "en_NG": "dd/MM/y, h:mm a",
    "ar_EG": "d‏/M‏/y h:mm a",
    "es_PA": "MM/dd/yy h:mm a",
    "en_PH": "dd/MM/y, h:mm a",
    "tl": "M/d/yy, h:mm a",
    "tl_PH": "M/d/yy, h:mm a",
    "en_IN": "dd/MM/yy, h:mm a",
    "ka": "dd.MM.yy, HH:mm",
    "ka_GE": "dd.MM.yy, HH:mm",
    "sr": "d.M.yy. HH:mm",
    "sr_CS": "d.M.yy. HH:mm",
    "sr_BA": "d.M.yy. HH:mm",
    "sk": "d. M. y H:mm",
    "en_MY": "dd/MM/y, h:mm a",
    "sh": "d.M.yy. HH:mm",
    "sh_CS": "d.M.yy. HH:mm",
    "sh_BA": "d.M.yy. HH:mm",
    "bs": "d.M.yy. HH:mm",
    "bs_BA": "d.M.yy. HH:mm",
    "hr": "dd. MM. y. HH:mm",
    "sl": "d. MM. yy HH:mm",
    "ro_MD": "dd.MM.y, HH:mm",
    "mk": "dd.M.yy HH:mm",
    "mk_MK": "dd.M.yy HH:mm",
    "et": "dd.MM.yy HH:mm",
    "lv": "dd.MM.yy HH:mm",
    "lt": "y-MM-dd HH:mm",
    "sq": "d.M.yy, h:mm a",
    "sq_AL": "d.M.yy, h:mm a",
    "eu": "yy/M/d HH:mm",
    "eu_ES": "yy/M/d HH:mm",
    "mt": "dd/MM/y HH:mm",
    "mt_MT": "dd/MM/y HH:mm",
    "ga": "dd/MM/y HH:mm",
    "ga_IE": "dd/MM/y HH:mm",
    "sh_ME": "d.M.yy. HH:mm",
    "is": "d.M.y, HH:mm",
    "cy": "dd/MM/yy HH:mm",
    "cy_GB": "dd/MM/yy HH:mm",
    "az_AZ": "dd.MM.yy HH:mm",
    "ky_KG": "d/M/yy HH:mm",
    "hi_IN": "d/M/yy, h:mm a",
    "en_PK": "dd/MM/y, h:mm a",
    "bn_BD": "d/M/yy h:mm a",
    "ar_QA": "d‏/M‏/y h:mm a",
    "be_BY": "d.MM.yy, HH:mm",
    "tg_TJ": "M/d/yy, h:mm a",
    "ms": "d/MM/yy h:mm a",
    "ms_BN": "d/MM/yy h:mm a",
    "zh_MO": "d/M/y ah:mm",
    "zh_SG": "dd/MM/yy ah:mm",
    "hy": "dd.MM.yy, HH:mm",
    "hi": "d/M/yy, h:mm a",
    "rm": "dd-MM-yy HH:mm",
    "rm_CH": "dd-MM-yy HH:mm",
    "lb": "dd.MM.yy HH:mm",
    "lb_LU": "dd.MM.yy HH:mm",
    "ur": "d/M/yy h:mm a",
    "pl_PL": "dd.MM.y, HH:mm",
    "hu_HU": "y. MM. dd. H:mm",
    "in_ID": "dd/MM/yy HH.mm",
    "tr_TR": "d.MM.y HH:mm",
    "zh_CN_STROKE": "y/M/d ah:mm",
    "zh_TW_STROKE": "y/M/d ah:mm",
    "zh_HK_STROKE": "d/M/y ah:mm",
    "zh_CN_PINYIN": "y/M/d ah:mm",
    "bn": "d/M/yy h:mm a",
    "ta": "d/M/yy, a h:mm",
    "ta_IN": "d/M/yy, a h:mm",
    "ar_DZ": "d‏/M‏/y h:mm a",
    "ar_IQ": "d‏/M‏/y h:mm a",
    "ar_LY": "d‏/M‏/y h:mm a",
    "ar_MA": "d‏/M‏/y HH:mm",
    "ar_OM": "d‏/M‏/y h:mm a",
    "ar_SD": "d‏/M‏/y h:mm a",
    "ar_SY": "d‏/M‏/y h:mm a",
    "ar_TN": "d‏/M‏/y h:mm a",
    "ar_YE": "d‏/M‏/y h:mm a",
    "en_HK": "d/M/y, h:mm a",
    "es_NI": "d/M/yy HH:mm",
    "es_US": "d/M/yy h:mm a",
    "eo": "yy-MM-dd HH:mm",
    "eo_US": "yy-MM-dd HH:mm",
    "iw_EO": "d.M.y, H:mm",
    "en_UG": "dd/MM/y, HH:mm",
    "en_KY": "dd/MM/y, h:mm a",
    "en_TT": "dd/MM/y, h:mm a",
    "ta_LK": "d/M/yy, HH:mm",
    "en_SH": "dd/MM/y, HH:mm",
    "so_DJ": "dd/MM/yy h:mm a",
    "dz_BT": "y-MM-dd ཆུ་ཚོད་ h སྐར་མ་ mm a",
    "fr_HT": "dd/MM/y HH:mm",
    "en_SX": "dd/MM/y, HH:mm",
    "en_SL": "dd/MM/y, h:mm a",
    "en_SC": "dd/MM/y, HH:mm",
    "en_FK": "dd/MM/y, HH:mm",
    "en_MW": "dd/MM/y, h:mm a",
    "en_ER": "dd/MM/y, h:mm a",
    "en_PG": "dd/MM/y, h:mm a",
    "en_AG": "dd/MM/y, h:mm a",
    "en_GI": "dd/MM/y, HH:mm",
    "en_RW": "dd/MM/y, HH:mm",
    "fa_IR": "y/M/d،‏ H:mm",
    "en_BW": "dd/MM/yy, HH:mm",
    "en_BS": "dd/MM/y, h:mm a",
    "en_VU": "dd/MM/y, h:mm a",
    "ti_ET": "dd/MM/yy h:mm a",
    "en_FJ": "dd/MM/y, h:mm a",
    "pt_ST": "dd/MM/yy, HH:mm",
    "fr_WF": "dd/MM/y HH:mm",
    "en_JM": "dd/MM/y, h:mm a",
    "en_MG": "dd/MM/y, HH:mm",
    "fr_MR": "dd/MM/y h:mm a",
    "en_WS": "dd/MM/y, h:mm a",
    "rn_BI": "d/M/y HH:mm",
    "fr_KM": "dd/MM/y HH:mm",
    "fr_GN": "dd/MM/y HH:mm",
    "en_SB": "dd/MM/y, h:mm a",
    "my_MM": "dd-MM-yy HH:mm",
    "pt_CV": "dd/MM/yy, HH:mm",
    "en_KE": "dd/MM/y, HH:mm",
    "nl_AW": "dd-MM-yy HH:mm",
    "pt_MZ": "dd/MM/yy, HH:mm",
    "yo_BJ": "dd/MM/y HH:mm",
    "en_LR": "dd/MM/y, h:mm a",
    "en_MU": "dd/MM/y, HH:mm",
    "en_BZ": "dd/MM/yy, HH:mm",
    "lu_CD": "d/M/y HH:mm",
    "es_CU": "d/M/yy HH:mm",
    "en_GM": "dd/MM/y, h:mm a",
    "en_CM": "dd/MM/y, HH:mm",
    "uz_LATN_UZ": "dd/MM/yy, HH:mm",
    "en_GY": "dd/MM/y, h:mm a",
    "ps_AF": "GGGGG y/M/d H:mm",
    "ne_NP": "y-MM-dd, HH:mm",
    "en_NA": "dd/MM/y, h:mm a",
    "so_SO": "dd/MM/yy h:mm a",
    "lo_LA": "d/M/y, H:mm",
    "en_SZ": "dd/MM/y, h:mm a",
    "en_TO": "dd/MM/y, h:mm a",
    "en_TZ": "dd/MM/y, HH:mm",
    "ko_KP": "yy. M. d. a h:mm",
    "sr_RS": "d.M.yy. HH:mm",
    "de_BE": "dd.MM.yy, HH:mm",
};