module.exports = {
    "en_US": "h:mm:ss a z",
    "en_GB": "HH:mm:ss z",
    "en_CA": "h:mm:ss a z",
    "da_DK": "HH.mm.ss z",
    "de_AT": "HH:mm:ss z",
    "de_CH": "HH:mm:ss z",
    "de_DE": "HH:mm:ss z",
    "de_LU": "HH:mm:ss z",
    "el_GR": "h:mm:ss a z",
    "en_IE": "HH:mm:ss z",
    "es_ES": "H:mm:ss z",
    "fi_FI": "H.mm.ss z",
    "fr_BE": "HH:mm:ss z",
    "fr_CA": "HH:mm:ss z",
    "fr_CH": "HH:mm:ss z",
    "fr_FR": "HH:mm:ss z",
    "fr_LU": "HH:mm:ss z",
    "it_CH": "HH:mm:ss z",
    "it_IT": "HH:mm:ss z",
    "ja_JP": "H:mm:ss z",
    "zh_CN": "z ah:mm:ss",
    "nl_BE": "HH:mm:ss z",
    "nl_NL": "HH:mm:ss z",
    "no_NO": "HH:mm:ss z",
    "pt_PT": "HH:mm:ss z",
    "sv_SE": "HH:mm:ss z",
    "zh_TW": "ah:mm:ss [z]",
    "ar": "h:mm:ss a z",
    "ca": "H:mm:ss z",
    "ca_ES": "H:mm:ss z",
    "ca_ES_EURO": "H:mm:ss z",
    "cs_CZ": "H:mm:ss z",
    "de": "HH:mm:ss z",
    "de_AT_EURO": "HH:mm:ss z",
    "de_DE_EURO": "HH:mm:ss z",
    "de_LU_EURO": "HH:mm:ss z",
    "en_AU": "h:mm:ss a z",
    "en_IE_EURO": "HH:mm:ss z",
    "en_NZ": "h:mm:ss a z",
    "en_ZA": "HH:mm:ss z",
    "es": "H:mm:ss z",
    "es_AR": "HH:mm:ss z",
    "es_CO": "h:mm:ss a z",
    "es_ES_EURO": "H:mm:ss z",
    "es_MX": "HH:mm:ss z",
    "es_VE": "h:mm:ss a z",
    "fi_FI_EURO": "H.mm.ss z",
    "fr": "HH:mm:ss z",
    "fr_FR_EURO": "HH:mm:ss z",
    "it": "HH:mm:ss z",
    "iw": "H:mm:ss z",
    "ja": "H:mm:ss z",
    "ko": "a h시 m분 s초 z",
    "no": "HH:mm:ss z",
    "pl": "HH:mm:ss z",
    "pt": "HH:mm:ss z",
    "ru": "H:mm:ss z",
    "sv": "HH:mm:ss z",
    "th": "H นาฬิกา mm นาที ss วินาที z",
    "tr": "HH:mm:ss z",
    "zh": "z ah:mm:ss",
    "zh_HK": "ah:mm:ss [z]",
    "ko_KR": "a h시 m분 s초 z",
    "pt_BR": "HH:mm:ss z",
    "hu": "H:mm:ss z",
    "fi": "H.mm.ss z",
    "nl": "HH:mm:ss z",
    "th_TH": "H นาฬิกา mm นาที ss วินาที z",
    "cs": "H:mm:ss z",
    "da": "HH.mm.ss z",
    "ar_AE": "h:mm:ss a z",
    "ar_BH": "h:mm:ss a z",
    "ar_JO": "h:mm:ss a z",
    "ar_KW": "h:mm:ss a z",
    "ar_LB": "h:mm:ss a z",
    "ar_SA": "h:mm:ss a z",
    "bg_BG": "H:mm:ss z",
    "en_BB": "h:mm:ss a z",
    "en_BM": "h:mm:ss a z",
    "en_GH": "h:mm:ss a z",
    "en_ID": "h:mm:ss a z",
    "en_SG": "h:mm:ss a z",
    "es_BO": "HH:mm:ss z",
    "es_CL": "HH:mm:ss z",
    "es_CR": "HH:mm:ss z",
    "es_EC": "HH:mm:ss z",
    "es_GT": "HH:mm:ss z",
    "es_HN": "HH:mm:ss z",
    "es_PE": "HH:mm:ss z",
    "es_PR": "h:mm:ss a z",
    "es_PY": "HH:mm:ss z",
    "es_SV": "HH:mm:ss z",
    "es_UY": "HH:mm:ss z",
    "et_EE": "HH:mm:ss z",
    "fr_MC": "HH:mm:ss z",
    "hr_HR": "HH:mm:ss z",
    "hy_AM": "HH:mm:ss z",
    "is_IS": "HH:mm:ss z",
    "iw_IL": "H:mm:ss z",
    "kk_KZ": "HH:mm:ss z",
    "km_KH": "h:mm:ss a z",
    "lt_LT": "HH:mm:ss z",
    "lv_LV": "HH:mm:ss z",
    "ms_MY": "h:mm:ss a z",
    "nl_SR": "HH:mm:ss z",
    "pt_AO": "HH:mm:ss z",
    "ro_RO": "HH:mm:ss z",
    "sk_SK": "H:mm:ss z",
    "sl_SI": "HH:mm:ss z",
    "ur_PK": "h:mm:ss a z",
    "vi_VN": "HH:mm:ss z",
    "in": "HH.mm.ss z",
    "ro": "HH:mm:ss z",
    "vi": "HH:mm:ss z",
    "uk": "HH:mm:ss z",
    "uk_UA": "HH:mm:ss z",
    "ru_RU": "H:mm:ss z",
    "el": "h:mm:ss a z",
    "bg": "H:mm:ss z",
    "es_DO": "h:mm:ss a z",
    "en_NG": "h:mm:ss a z",
    "ar_EG": "h:mm:ss a z",
    "es_PA": "h:mm:ss a z",
    "en_PH": "h:mm:ss a z",
    "tl": "h:mm:ss a z",
    "tl_PH": "h:mm:ss a z",
    "en_IN": "h:mm:ss a z",
    "ka": "HH:mm:ss z",
    "ka_GE": "HH:mm:ss z",
    "sr": "HH:mm:ss z",
    "sr_CS": "HH:mm:ss z",
    "sr_BA": "HH:mm:ss z",
    "sk": "H:mm:ss z",
    "en_MY": "h:mm:ss a z",
    "sh": "HH:mm:ss z",
    "sh_CS": "HH:mm:ss z",
    "sh_BA": "HH:mm:ss z",
    "bs": "HH:mm:ss z",
    "bs_BA": "HH:mm:ss z",
    "hr": "HH:mm:ss z",
    "sl": "HH:mm:ss z",
    "ro_MD": "HH:mm:ss z",
    "mk": "HH:mm:ss z",
    "mk_MK": "HH:mm:ss z",
    "et": "HH:mm:ss z",
    "lv": "HH:mm:ss z",
    "lt": "HH:mm:ss z",
    "sq": "h:mm:ss a, z",
    "sq_AL": "h:mm:ss a, z",
    "eu": "HH:mm:ss (z)",
    "eu_ES": "HH:mm:ss (z)",
    "mt": "HH:mm:ss z",
    "mt_MT": "HH:mm:ss z",
    "ga": "HH:mm:ss z",
    "ga_IE": "HH:mm:ss z",
    "sh_ME": "HH:mm:ss z",
    "is": "HH:mm:ss z",
    "cy": "HH:mm:ss z",
    "cy_GB": "HH:mm:ss z",
    "az_AZ": "HH:mm:ss z",
    "ky_KG": "HH:mm:ss z",
    "hi_IN": "h:mm:ss a z",
    "en_PK": "h:mm:ss a z",
    "bn_BD": "h:mm:ss a z",
    "ar_QA": "h:mm:ss a z",
    "be_BY": "HH:mm:ss z",
    "tg_TJ": "h:mm:ss a z",
    "ms": "h:mm:ss a z",
    "ms_BN": "h:mm:ss a z",
    "zh_MO": "ah:mm:ss [z]",
    "zh_SG": "z ah:mm:ss",
    "hy": "HH:mm:ss z",
    "hi": "h:mm:ss a z",
    "rm": "HH:mm:ss z",
    "rm_CH": "HH:mm:ss z",
    "lb": "HH:mm:ss z",
    "lb_LU": "HH:mm:ss z",
    "ur": "h:mm:ss a z",
    "pl_PL": "HH:mm:ss z",
    "hu_HU": "H:mm:ss z",
    "in_ID": "HH.mm.ss z",
    "tr_TR": "HH:mm:ss z",
    "zh_CN_STROKE": "z ah:mm:ss",
    "zh_TW_STROKE": "ah:mm:ss [z]",
    "zh_HK_STROKE": "ah:mm:ss [z]",
    "zh_CN_PINYIN": "z ah:mm:ss",
    "bn": "h:mm:ss a z",
    "ta": "a h:mm:ss z",
    "ta_IN": "a h:mm:ss z",
    "ar_DZ": "h:mm:ss a z",
    "ar_IQ": "h:mm:ss a z",
    "ar_LY": "h:mm:ss a z",
    "ar_MA": "HH:mm:ss z",
    "ar_OM": "h:mm:ss a z",
    "ar_SD": "h:mm:ss a z",
    "ar_SY": "h:mm:ss a z",
    "ar_TN": "h:mm:ss a z",
    "ar_YE": "h:mm:ss a z",
    "en_HK": "h:mm:ss a z",
    "es_NI": "HH:mm:ss z",
    "es_US": "h:mm:ss a z",
    "eo": "HH:mm:ss z",
    "eo_US": "HH:mm:ss z",
    "iw_EO": "H:mm:ss z",
    "en_UG": "HH:mm:ss z",
    "en_KY": "h:mm:ss a z",
    "en_TT": "h:mm:ss a z",
    "ta_LK": "HH:mm:ss z",
    "en_SH": "HH:mm:ss z",
    "so_DJ": "h:mm:ss a z",
    "dz_BT": "ཆུ་ཚོད་ h སྐར་མ་ mm:ss a z",
    "fr_HT": "HH:mm:ss z",
    "en_SX": "HH:mm:ss z",
    "en_SL": "h:mm:ss a z",
    "en_SC": "HH:mm:ss z",
    "en_FK": "HH:mm:ss z",
    "en_MW": "h:mm:ss a z",
    "en_ER": "h:mm:ss a z",
    "en_PG": "h:mm:ss a z",
    "en_AG": "h:mm:ss a z",
    "en_GI": "HH:mm:ss z",
    "en_RW": "HH:mm:ss z",
    "fa_IR": "H:mm:ss (z)",
    "en_BW": "HH:mm:ss z",
    "en_BS": "h:mm:ss a z",
    "en_VU": "h:mm:ss a z",
    "ti_ET": "h:mm:ss a z",
    "en_FJ": "h:mm:ss a z",
    "pt_ST": "HH:mm:ss z",
    "fr_WF": "HH:mm:ss z",
    "en_JM": "h:mm:ss a z",
    "en_MG": "HH:mm:ss z",
    "fr_MR": "h:mm:ss a z",
    "en_WS": "h:mm:ss a z",
    "rn_BI": "HH:mm:ss z",
    "fr_KM": "HH:mm:ss z",
    "fr_GN": "HH:mm:ss z",
    "en_SB": "h:mm:ss a z",
    "my_MM": "z HH:mm:ss",
    "pt_CV": "HH:mm:ss z",
    "en_KE": "HH:mm:ss z",
    "nl_AW": "HH:mm:ss z",
    "pt_MZ": "HH:mm:ss z",
    "yo_BJ": "HH:mm:ss z",
    "en_LR": "h:mm:ss a z",
    "en_MU": "HH:mm:ss z",
    "en_BZ": "HH:mm:ss z",
    "lu_CD": "HH:mm:ss z",
    "es_CU": "HH:mm:ss z",
    "en_GM": "h:mm:ss a z",
    "en_CM": "HH:mm:ss z",
    "uz_LATN_UZ": "H:mm:ss (z)",
    "en_GY": "h:mm:ss a z",
    "ps_AF": "H:mm:ss (z)",
    "ne_NP": "HH:mm:ss z",
    "en_NA": "h:mm:ss a z",
    "so_SO": "h:mm:ss a z",
    "lo_LA": "H ໂມງ m ນາທີ ss ວິນາທີ z",
    "en_SZ": "h:mm:ss a z",
    "en_TO": "h:mm:ss a z",
    "en_TZ": "HH:mm:ss z",
    "ko_KP": "a h시 m분 s초 z",
    "sr_RS": "HH:mm:ss z",
    "de_BE": "HH:mm:ss z",
};