module.exports = {
    "en_US": "EEEE, MMMM d, y",
    "en_GB": "EEEE, d MMMM y",
    "en_CA": "EEEE, MMMM d, y",
    "da_DK": "EEEE 'den' d. MMMM y",
    "de_AT": "EEEE, d. MMMM y",
    "de_CH": "EEEE, d. MMMM y",
    "de_DE": "EEEE, d. MMMM y",
    "de_LU": "EEEE, d. MMMM y",
    "el_GR": "EEEE, d MMMM y",
    "en_IE": "EEEE d MMMM y",
    "es_ES": "EEEE, d 'de' MMMM 'de' y",
    "fi_FI": "cccc d. MMMM y",
    "fr_BE": "EEEE d MMMM y",
    "fr_CA": "EEEE d MMMM y",
    "fr_CH": "EEEE, d MMMM y",
    "fr_FR": "EEEE d MMMM y",
    "fr_LU": "EEEE d MMMM y",
    "it_CH": "EEEE, d MMMM y",
    "it_IT": "EEEE d MMMM y",
    "ja_JP": "y年M月d日EEEE",
    "zh_CN": "y年M月d日EEEE",
    "nl_BE": "EEEE d MMMM y",
    "nl_NL": "EEEE d MMMM y",
    "no_NO": "EEEE d. MMMM y",
    "pt_PT": "EEEE, d 'de' MMMM 'de' y",
    "sv_SE": "EEEE d MMMM y",
    "zh_TW": "y年M月d日 EEEE",
    "ar": "EEEE، d MMMM، y",
    "ca": "EEEE, d MMMM 'de' y",
    "ca_ES": "EEEE, d MMMM 'de' y",
    "ca_ES_EURO": "EEEE, d MMMM 'de' y",
    "cs_CZ": "EEEE d. MMMM y",
    "de": "EEEE, d. MMMM y",
    "de_AT_EURO": "EEEE, d. MMMM y",
    "de_DE_EURO": "EEEE, d. MMMM y",
    "de_LU_EURO": "EEEE, d. MMMM y",
    "en_AU": "EEEE, d MMMM y",
    "en_IE_EURO": "EEEE d MMMM y",
    "en_NZ": "EEEE, d MMMM y",
    "en_ZA": "EEEE, dd MMMM y",
    "es": "EEEE, d 'de' MMMM 'de' y",
    "es_AR": "EEEE, d 'de' MMMM 'de' y",
    "es_CO": "EEEE, d 'de' MMMM 'de' y",
    "es_ES_EURO": "EEEE, d 'de' MMMM 'de' y",
    "es_MX": "EEEE, d 'de' MMMM 'de' y",
    "es_VE": "EEEE, d 'de' MMMM 'de' y",
    "fi_FI_EURO": "cccc d. MMMM y",
    "fr": "EEEE d MMMM y",
    "fr_FR_EURO": "EEEE d MMMM y",
    "it": "EEEE d MMMM y",
    "iw": "EEEE, d בMMMM y",
    "ja": "y年M月d日EEEE",
    "ko": "y년 M월 d일 EEEE",
    "no": "EEEE d. MMMM y",
    "pl": "EEEE, d MMMM y",
    "pt": "EEEE, d 'de' MMMM 'de' y",
    "ru": "EEEE, d MMMM y 'г'.",
    "sv": "EEEE d MMMM y",
    "th": "EEEEที่ d MMMM G y",
    "tr": "d MMMM y EEEE",
    "zh": "y年M月d日EEEE",
    "zh_HK": "y年M月d日EEEE",
    "ko_KR": "y년 M월 d일 EEEE",
    "pt_BR": "EEEE, d 'de' MMMM 'de' y",
    "hu": "y. MMMM d., EEEE",
    "fi": "cccc d. MMMM y",
    "nl": "EEEE d MMMM y",
    "th_TH": "EEEEที่ d MMMM G y",
    "cs": "EEEE d. MMMM y",
    "da": "EEEE 'den' d. MMMM y",
    "ar_AE": "EEEE، d MMMM، y",
    "ar_BH": "EEEE، d MMMM، y",
    "ar_JO": "EEEE، d MMMM، y",
    "ar_KW": "EEEE، d MMMM، y",
    "ar_LB": "EEEE، d MMMM، y",
    "ar_SA": "EEEE، d MMMM، y G",
    "bg_BG": "EEEE, d MMMM y 'г'.",
    "en_BB": "EEEE, d MMMM y",
    "en_BM": "EEEE, d MMMM y",
    "en_GH": "EEEE, d MMMM y",
    "en_ID": "EEEE, MMMM d, y",
    "en_SG": "EEEE, d MMMM y",
    "es_BO": "EEEE, d 'de' MMMM 'de' y",
    "es_CL": "EEEE, d 'de' MMMM 'de' y",
    "es_CR": "EEEE, d 'de' MMMM 'de' y",
    "es_EC": "EEEE, d 'de' MMMM 'de' y",
    "es_GT": "EEEE, d 'de' MMMM 'de' y",
    "es_HN": "EEEE dd 'de' MMMM 'de' y",
    "es_PE": "EEEE, d 'de' MMMM 'de' y",
    "es_PR": "EEEE, d 'de' MMMM 'de' y",
    "es_PY": "EEEE, d 'de' MMMM 'de' y",
    "es_SV": "EEEE, d 'de' MMMM 'de' y",
    "es_UY": "EEEE, d 'de' MMMM 'de' y",
    "et_EE": "EEEE, d. MMMM y",
    "fr_MC": "EEEE d MMMM y",
    "hr_HR": "EEEE, d. MMMM y.",
    "hy_AM": "y թ. MMMM d, EEEE",
    "is_IS": "EEEE, d. MMMM y",
    "iw_IL": "EEEE, d בMMMM y",
    "kk_KZ": "y 'ж'. d MMMM, EEEE",
    "km_KH": "EEEE d MMMM y",
    "lt_LT": "y 'm'. MMMM d 'd'., EEEE",
    "lv_LV": "EEEE, y. 'gada' d. MMMM",
    "ms_MY": "EEEE, d MMMM y",
    "nl_SR": "EEEE d MMMM y",
    "pt_AO": "EEEE, d 'de' MMMM 'de' y",
    "ro_RO": "EEEE, d MMMM y",
    "sk_SK": "EEEE, d. MMMM y",
    "sl_SI": "EEEE, dd. MMMM y",
    "ur_PK": "EEEE، d MMMM، y",
    "vi_VN": "EEEE, d MMMM, y",
    "in": "EEEE, dd MMMM y",
    "ro": "EEEE, d MMMM y",
    "vi": "EEEE, d MMMM, y",
    "uk": "EEEE, d MMMM y 'р'.",
    "uk_UA": "EEEE, d MMMM y 'р'.",
    "ru_RU": "EEEE, d MMMM y 'г'.",
    "el": "EEEE, d MMMM y",
    "bg": "EEEE, d MMMM y 'г'.",
    "es_DO": "EEEE, d 'de' MMMM 'de' y",
    "en_NG": "EEEE, d MMMM y",
    "ar_EG": "EEEE، d MMMM، y",
    "es_PA": "EEEE, d 'de' MMMM 'de' y",
    "en_PH": "EEEE, d MMMM y",
    "tl": "EEEE, MMMM d, y",
    "tl_PH": "EEEE, MMMM d, y",
    "en_IN": "EEEE d MMMM y",
    "ka": "EEEE, dd MMMM, y",
    "ka_GE": "EEEE, dd MMMM, y",
    "sr": "EEEE, dd. MMMM y.",
    "sr_CS": "EEEE, dd. MMMM y.",
    "sr_BA": "EEEE, dd. MMMM y.",
    "sk": "EEEE, d. MMMM y",
    "en_MY": "EEEE, d MMMM y",
    "sh": "EEEE, dd. MMMM y.",
    "sh_CS": "EEEE, dd. MMMM y.",
    "sh_BA": "EEEE, dd. MMMM y.",
    "bs": "EEEE, d. MMMM y.",
    "bs_BA": "EEEE, d. MMMM y.",
    "hr": "EEEE, d. MMMM y.",
    "sl": "EEEE, dd. MMMM y",
    "ro_MD": "EEEE, d MMMM y",
    "mk": "EEEE, dd MMMM y",
    "mk_MK": "EEEE, dd MMMM y",
    "et": "EEEE, d. MMMM y",
    "lv": "EEEE, y. 'gada' d. MMMM",
    "lt": "y 'm'. MMMM d 'd'., EEEE",
    "sq": "EEEE, d MMMM y",
    "sq_AL": "EEEE, d MMMM y",
    "eu": "y('e')'ko' MMMM d, EEEE",
    "eu_ES": "y('e')'ko' MMMM d, EEEE",
    "mt": "EEEE, d 'ta'’ MMMM y",
    "mt_MT": "EEEE, d 'ta'’ MMMM y",
    "ga": "EEEE d MMMM y",
    "ga_IE": "EEEE d MMMM y",
    "sh_ME": "EEEE, dd. MMMM y.",
    "is": "EEEE, d. MMMM y",
    "cy": "EEEE, d MMMM y",
    "cy_GB": "EEEE, d MMMM y",
    "az_AZ": "d MMMM y, EEEE",
    "ky_KG": "y-'ж'., d-MMMM, EEEE",
    "hi_IN": "EEEE, d MMMM y",
    "en_PK": "EEEE, d MMMM y",
    "bn_BD": "EEEE, d MMMM, y",
    "ar_QA": "EEEE، d MMMM، y",
    "be_BY": "EEEE, d MMMM y 'г'.",
    "tg_TJ": "EEEE, MMMM d, y",
    "ms": "EEEE, d MMMM y",
    "ms_BN": "dd MMMM y",
    "zh_MO": "y年M月d日EEEE",
    "zh_SG": "y年M月d日EEEE",
    "hy": "y թ. MMMM d, EEEE",
    "hi": "EEEE, d MMMM y",
    "rm": "EEEE, 'ils' d 'da' MMMM y",
    "rm_CH": "EEEE, 'ils' d 'da' MMMM y",
    "lb": "EEEE, d. MMMM y",
    "lb_LU": "EEEE, d. MMMM y",
    "ur": "EEEE، d MMMM، y",
    "pl_PL": "EEEE, d MMMM y",
    "hu_HU": "y. MMMM d., EEEE",
    "in_ID": "EEEE, dd MMMM y",
    "tr_TR": "d MMMM y EEEE",
    "zh_CN_STROKE": "y年M月d日EEEE",
    "zh_TW_STROKE": "y年M月d日 EEEE",
    "zh_HK_STROKE": "y年M月d日EEEE",
    "zh_CN_PINYIN": "y年M月d日EEEE",
    "bn": "EEEE, d MMMM, y",
    "ta": "EEEE, d MMMM, y",
    "ta_IN": "EEEE, d MMMM, y",
    "ar_DZ": "EEEE، d MMMM، y",
    "ar_IQ": "EEEE، d MMMM، y",
    "ar_LY": "EEEE، d MMMM، y",
    "ar_MA": "EEEE، d MMMM، y",
    "ar_OM": "EEEE، d MMMM، y",
    "ar_SD": "EEEE، d MMMM، y",
    "ar_SY": "EEEE، d MMMM، y",
    "ar_TN": "EEEE، d MMMM، y",
    "ar_YE": "EEEE، d MMMM، y",
    "en_HK": "EEEE, d MMMM y",
    "es_NI": "EEEE, d 'de' MMMM 'de' y",
    "es_US": "EEEE, d 'de' MMMM 'de' y",
    "eo": "EEEE, d-'a' 'de' MMMM y",
    "eo_US": "EEEE, d-'a' 'de' MMMM y",
    "iw_EO": "EEEE, d בMMMM y",
    "en_UG": "EEEE, d MMMM y",
    "en_KY": "EEEE, d MMMM y",
    "en_TT": "EEEE, d MMMM y",
    "ta_LK": "EEEE, d MMMM, y",
    "en_SH": "EEEE, d MMMM y",
    "so_DJ": "EEEE, MMMM dd, y",
    "dz_BT": "EEEE, སྤྱི་ལོ་y MMMM ཚེས་dd",
    "fr_HT": "EEEE d MMMM y",
    "en_SX": "EEEE, d MMMM y",
    "en_SL": "EEEE, d MMMM y",
    "en_SC": "EEEE, d MMMM y",
    "en_FK": "EEEE, d MMMM y",
    "en_MW": "EEEE, d MMMM y",
    "en_ER": "EEEE, d MMMM y",
    "en_PG": "EEEE, d MMMM y",
    "en_AG": "EEEE, d MMMM y",
    "en_GI": "EEEE, d MMMM y",
    "en_RW": "EEEE, d MMMM y",
    "fa_IR": "y MMMM d, EEEE",
    "en_BW": "EEEE, dd MMMM y",
    "en_BS": "EEEE, d MMMM y",
    "en_VU": "EEEE, d MMMM y",
    "ti_ET": "EEEE፣ dd MMMM መዓልቲ y G",
    "en_FJ": "EEEE, d MMMM y",
    "pt_ST": "EEEE, d 'de' MMMM 'de' y",
    "fr_WF": "EEEE d MMMM y",
    "en_JM": "EEEE, d MMMM y",
    "en_MG": "EEEE, d MMMM y",
    "fr_MR": "EEEE d MMMM y",
    "en_WS": "EEEE, d MMMM y",
    "rn_BI": "EEEE d MMMM y",
    "fr_KM": "EEEE d MMMM y",
    "fr_GN": "EEEE d MMMM y",
    "en_SB": "EEEE, d MMMM y",
    "my_MM": "EEEE d MMMM y",
    "pt_CV": "EEEE, d 'de' MMMM 'de' y",
    "en_KE": "EEEE, d MMMM y",
    "nl_AW": "EEEE d MMMM y",
    "pt_MZ": "EEEE, d 'de' MMMM 'de' y",
    "yo_BJ": "EEEE, d MMMM y",
    "en_LR": "EEEE, d MMMM y",
    "en_MU": "EEEE, d MMMM y",
    "en_BZ": "EEEE, dd MMMM y",
    "lu_CD": "EEEE d MMMM y",
    "es_CU": "EEEE, d 'de' MMMM 'de' y",
    "en_GM": "EEEE, d MMMM y",
    "en_CM": "EEEE, d MMMM y",
    "uz_LATN_UZ": "EEEE, d-MMMM, y",
    "en_GY": "EEEE, d MMMM y",
    "ps_AF": "EEEE د G y د MMMM d",
    "ne_NP": "y MMMM d, EEEE",
    "en_NA": "EEEE, d MMMM y",
    "so_SO": "EEEE, MMMM dd, y",
    "lo_LA": "EEEE ທີ d MMMM G y",
    "en_SZ": "EEEE, d MMMM y",
    "en_TO": "EEEE, d MMMM y",
    "en_TZ": "EEEE, d MMMM y",
    "ko_KP": "y년 M월 d일 EEEE",
    "sr_RS": "EEEE, dd. MMMM y.",
    "de_BE": "EEEE, d. MMMM y",
};