module.exports = {
    "en_US": "MMMM d, y",
    "en_GB": "d MMMM y",
    "en_CA": "MMMM d, y",
    "da_DK": "d. MMMM y",
    "de_AT": "d. MMMM y",
    "de_CH": "d. MMMM y",
    "de_DE": "d. MMMM y",
    "de_LU": "d. MMMM y",
    "el_GR": "d MMMM y",
    "en_IE": "d MMMM y",
    "es_ES": "d 'de' MMMM 'de' y",
    "fi_FI": "d. MMMM y",
    "fr_BE": "d MMMM y",
    "fr_CA": "d MMMM y",
    "fr_CH": "d MMMM y",
    "fr_FR": "d MMMM y",
    "fr_LU": "d MMMM y",
    "it_CH": "d MMMM y",
    "it_IT": "d MMMM y",
    "ja_JP": "y年M月d日",
    "zh_CN": "y年M月d日",
    "nl_BE": "d MMMM y",
    "nl_NL": "d MMMM y",
    "no_NO": "d. MMMM y",
    "pt_PT": "d 'de' MMMM 'de' y",
    "sv_SE": "d MMMM y",
    "zh_TW": "y年M月d日",
    "ar": "d MMMM، y",
    "ca": "d MMMM 'de' y",
    "ca_ES": "d MMMM 'de' y",
    "ca_ES_EURO": "d MMMM 'de' y",
    "cs_CZ": "d. MMMM y",
    "de": "d. MMMM y",
    "de_AT_EURO": "d. MMMM y",
    "de_DE_EURO": "d. MMMM y",
    "de_LU_EURO": "d. MMMM y",
    "en_AU": "d MMMM y",
    "en_IE_EURO": "d MMMM y",
    "en_NZ": "d MMMM y",
    "en_ZA": "dd MMMM y",
    "es": "d 'de' MMMM 'de' y",
    "es_AR": "d 'de' MMMM 'de' y",
    "es_CO": "d 'de' MMMM 'de' y",
    "es_ES_EURO": "d 'de' MMMM 'de' y",
    "es_MX": "d 'de' MMMM 'de' y",
    "es_VE": "d 'de' MMMM 'de' y",
    "fi_FI_EURO": "d. MMMM y",
    "fr": "d MMMM y",
    "fr_FR_EURO": "d MMMM y",
    "it": "d MMMM y",
    "iw": "d בMMMM y",
    "ja": "y年M月d日",
    "ko": "y년 M월 d일",
    "no": "d. MMMM y",
    "pl": "d MMMM y",
    "pt": "d 'de' MMMM 'de' y",
    "ru": "d MMMM y 'г'.",
    "sv": "d MMMM y",
    "th": "d MMMM y",
    "tr": "d MMMM y",
    "zh": "y年M月d日",
    "zh_HK": "y年M月d日",
    "ko_KR": "y년 M월 d일",
    "pt_BR": "d 'de' MMMM 'de' y",
    "hu": "y. MMMM d.",
    "fi": "d. MMMM y",
    "nl": "d MMMM y",
    "th_TH": "d MMMM y",
    "cs": "d. MMMM y",
    "da": "d. MMMM y",
    "ar_AE": "d MMMM، y",
    "ar_BH": "d MMMM، y",
    "ar_JO": "d MMMM، y",
    "ar_KW": "d MMMM، y",
    "ar_LB": "d MMMM، y",
    "ar_SA": "d MMMM، y G",
    "bg_BG": "d MMMM y 'г'.",
    "en_BB": "d MMMM y",
    "en_BM": "d MMMM y",
    "en_GH": "d MMMM y",
    "en_ID": "MMMM d, y",
    "en_SG": "d MMMM y",
    "es_BO": "d 'de' MMMM 'de' y",
    "es_CL": "d 'de' MMMM 'de' y",
    "es_CR": "d 'de' MMMM 'de' y",
    "es_EC": "d 'de' MMMM 'de' y",
    "es_GT": "d 'de' MMMM 'de' y",
    "es_HN": "dd 'de' MMMM 'de' y",
    "es_PE": "d 'de' MMMM 'de' y",
    "es_PR": "d 'de' MMMM 'de' y",
    "es_PY": "d 'de' MMMM 'de' y",
    "es_SV": "d 'de' MMMM 'de' y",
    "es_UY": "d 'de' MMMM 'de' y",
    "et_EE": "d. MMMM y",
    "fr_MC": "d MMMM y",
    "hr_HR": "d. MMMM y.",
    "hy_AM": "dd MMMM, y թ.",
    "is_IS": "d. MMMM y",
    "iw_IL": "d בMMMM y",
    "kk_KZ": "y 'ж'. d MMMM",
    "km_KH": "d MMMM y",
    "lt_LT": "y 'm'. MMMM d 'd'.",
    "lv_LV": "y. 'gada' d. MMMM",
    "ms_MY": "d MMMM y",
    "nl_SR": "d MMMM y",
    "pt_AO": "d 'de' MMMM 'de' y",
    "ro_RO": "d MMMM y",
    "sk_SK": "d. MMMM y",
    "sl_SI": "dd. MMMM y",
    "ur_PK": "d MMMM، y",
    "vi_VN": "d MMMM, y",
    "in": "d MMMM y",
    "ro": "d MMMM y",
    "vi": "d MMMM, y",
    "uk": "d MMMM y 'р'.",
    "uk_UA": "d MMMM y 'р'.",
    "ru_RU": "d MMMM y 'г'.",
    "el": "d MMMM y",
    "bg": "d MMMM y 'г'.",
    "es_DO": "d 'de' MMMM 'de' y",
    "en_NG": "d MMMM y",
    "ar_EG": "d MMMM، y",
    "es_PA": "d 'de' MMMM 'de' y",
    "en_PH": "d MMMM y",
    "tl": "MMMM d, y",
    "tl_PH": "MMMM d, y",
    "en_IN": "d MMMM y",
    "ka": "d MMMM, y",
    "ka_GE": "d MMMM, y",
    "sr": "dd. MMMM y.",
    "sr_CS": "dd. MMMM y.",
    "sr_BA": "dd. MMMM y.",
    "sk": "d. MMMM y",
    "en_MY": "d MMMM y",
    "sh": "dd. MMMM y.",
    "sh_CS": "dd. MMMM y.",
    "sh_BA": "dd. MMMM y.",
    "bs": "d. MMMM y.",
    "bs_BA": "d. MMMM y.",
    "hr": "d. MMMM y.",
    "sl": "dd. MMMM y",
    "ro_MD": "d MMMM y",
    "mk": "dd MMMM y",
    "mk_MK": "dd MMMM y",
    "et": "d. MMMM y",
    "lv": "y. 'gada' d. MMMM",
    "lt": "y 'm'. MMMM d 'd'.",
    "sq": "d MMMM y",
    "sq_AL": "d MMMM y",
    "eu": "y('e')'ko' MMMM d",
    "eu_ES": "y('e')'ko' MMMM d",
    "mt": "d 'ta'’ MMMM y",
    "mt_MT": "d 'ta'’ MMMM y",
    "ga": "d MMMM y",
    "ga_IE": "d MMMM y",
    "sh_ME": "dd. MMMM y.",
    "is": "d. MMMM y",
    "cy": "d MMMM y",
    "cy_GB": "d MMMM y",
    "az_AZ": "d MMMM y",
    "ky_KG": "y-'ж'., d-MMMM",
    "hi_IN": "d MMMM y",
    "en_PK": "d MMMM y",
    "bn_BD": "d MMMM, y",
    "ar_QA": "d MMMM، y",
    "be_BY": "d MMMM y 'г'.",
    "tg_TJ": "MMMM d, y",
    "ms": "d MMMM y",
    "ms_BN": "d MMMM y",
    "zh_MO": "y年M月d日",
    "zh_SG": "y年M月d日",
    "hy": "dd MMMM, y թ.",
    "hi": "d MMMM y",
    "rm": "d 'da' MMMM y",
    "rm_CH": "d 'da' MMMM y",
    "lb": "d. MMMM y",
    "lb_LU": "d. MMMM y",
    "ur": "d MMMM، y",
    "pl_PL": "d MMMM y",
    "hu_HU": "y. MMMM d.",
    "in_ID": "d MMMM y",
    "tr_TR": "d MMMM y",
    "zh_CN_STROKE": "y年M月d日",
    "zh_TW_STROKE": "y年M月d日",
    "zh_HK_STROKE": "y年M月d日",
    "zh_CN_PINYIN": "y年M月d日",
    "bn": "d MMMM, y",
    "ta": "d MMMM, y",
    "ta_IN": "d MMMM, y",
    "ar_DZ": "d MMMM، y",
    "ar_IQ": "d MMMM، y",
    "ar_LY": "d MMMM، y",
    "ar_MA": "d MMMM، y",
    "ar_OM": "d MMMM، y",
    "ar_SD": "d MMMM، y",
    "ar_SY": "d MMMM، y",
    "ar_TN": "d MMMM، y",
    "ar_YE": "d MMMM، y",
    "en_HK": "d MMMM y",
    "es_NI": "d 'de' MMMM 'de' y",
    "es_US": "d 'de' MMMM 'de' y",
    "eo": "y-MMMM-dd",
    "eo_US": "y-MMMM-dd",
    "iw_EO": "d בMMMM y",
    "en_UG": "d MMMM y",
    "en_KY": "d MMMM y",
    "en_TT": "d MMMM y",
    "ta_LK": "d MMMM, y",
    "en_SH": "d MMMM y",
    "so_DJ": "dd MMMM y",
    "dz_BT": "སྤྱི་ལོ་y MMMM ཚེས་ dd",
    "fr_HT": "d MMMM y",
    "en_SX": "d MMMM y",
    "en_SL": "d MMMM y",
    "en_SC": "d MMMM y",
    "en_FK": "d MMMM y",
    "en_MW": "d MMMM y",
    "en_ER": "d MMMM y",
    "en_PG": "d MMMM y",
    "en_AG": "d MMMM y",
    "en_GI": "d MMMM y",
    "en_RW": "d MMMM y",
    "fa_IR": "d MMMM y",
    "en_BW": "dd MMMM y",
    "en_BS": "d MMMM y",
    "en_VU": "d MMMM y",
    "ti_ET": "dd MMMM y",
    "en_FJ": "d MMMM y",
    "pt_ST": "d 'de' MMMM 'de' y",
    "fr_WF": "d MMMM y",
    "en_JM": "d MMMM y",
    "en_MG": "d MMMM y",
    "fr_MR": "d MMMM y",
    "en_WS": "d MMMM y",
    "rn_BI": "d MMMM y",
    "fr_KM": "d MMMM y",
    "fr_GN": "d MMMM y",
    "en_SB": "d MMMM y",
    "my_MM": "d MMMM y",
    "pt_CV": "d 'de' MMMM 'de' y",
    "en_KE": "d MMMM y",
    "nl_AW": "d MMMM y",
    "pt_MZ": "d 'de' MMMM 'de' y",
    "yo_BJ": "d MMMM y",
    "en_LR": "d MMMM y",
    "en_MU": "d MMMM y",
    "en_BZ": "dd MMMM y",
    "lu_CD": "d MMMM y",
    "es_CU": "d 'de' MMMM 'de' y",
    "en_GM": "d MMMM y",
    "en_CM": "d MMMM y",
    "uz_LATN_UZ": "d-MMMM, y",
    "en_GY": "d MMMM y",
    "ps_AF": "د G y د MMMM d",
    "ne_NP": "y MMMM d",
    "en_NA": "d MMMM y",
    "so_SO": "dd MMMM y",
    "lo_LA": "d MMMM y",
    "en_SZ": "d MMMM y",
    "en_TO": "d MMMM y",
    "en_TZ": "d MMMM y",
    "ko_KP": "y년 M월 d일",
    "sr_RS": "dd. MMMM y.",
    "de_BE": "d. MMMM y",
};