module.exports = {
    "en_US": "MMM d, y",
    "en_GB": "d MMM y",
    "en_CA": "MMM d, y",
    "da_DK": "d. MMM y",
    "de_AT": "dd.MM.y",
    "de_CH": "dd.MM.y",
    "de_DE": "dd.MM.y",
    "de_LU": "dd.MM.y",
    "el_GR": "d MMM y",
    "en_IE": "d MMM y",
    "es_ES": "d MMM y",
    "fi_FI": "d.M.y",
    "fr_BE": "d MMM y",
    "fr_CA": "d MMM y",
    "fr_CH": "d MMM y",
    "fr_FR": "d MMM y",
    "fr_LU": "d MMM y",
    "it_CH": "d MMM y",
    "it_IT": "dd MMM y",
    "ja_JP": "y/MM/dd",
    "zh_CN": "y年M月d日",
    "nl_BE": "d MMM y",
    "nl_NL": "d MMM y",
    "no_NO": "d. MMM y",
    "pt_PT": "dd/MM/y",
    "sv_SE": "d MMM y",
    "zh_TW": "y年M月d日",
    "ar": "dd‏/MM‏/y",
    "ca": "d MMM y",
    "ca_ES": "d MMM y",
    "ca_ES_EURO": "d MMM y",
    "cs_CZ": "d. M. y",
    "de": "dd.MM.y",
    "de_AT_EURO": "dd.MM.y",
    "de_DE_EURO": "dd.MM.y",
    "de_LU_EURO": "dd.MM.y",
    "en_AU": "d MMM y",
    "en_IE_EURO": "d MMM y",
    "en_NZ": "d/MM/y",
    "en_ZA": "dd MMM y",
    "es": "d MMM y",
    "es_AR": "d MMM y",
    "es_CO": "d/MM/y",
    "es_ES_EURO": "d MMM y",
    "es_MX": "dd/MM/y",
    "es_VE": "d MMM y",
    "fi_FI_EURO": "d.M.y",
    "fr": "d MMM y",
    "fr_FR_EURO": "d MMM y",
    "it": "dd MMM y",
    "iw": "d בMMM y",
    "ja": "y/MM/dd",
    "ko": "y. M. d.",
    "no": "d. MMM y",
    "pl": "d MMM y",
    "pt": "d 'de' MMM 'de' y",
    "ru": "d MMM y 'г'.",
    "sv": "d MMM y",
    "th": "d MMM y",
    "tr": "d MMM y",
    "zh": "y年M月d日",
    "zh_HK": "y年M月d日",
    "ko_KR": "y. M. d.",
    "pt_BR": "d 'de' MMM 'de' y",
    "hu": "y. MMM d.",
    "fi": "d.M.y",
    "nl": "d MMM y",
    "th_TH": "d MMM y",
    "cs": "d. M. y",
    "da": "d. MMM y",
    "ar_AE": "dd‏/MM‏/y",
    "ar_BH": "dd‏/MM‏/y",
    "ar_JO": "dd‏/MM‏/y",
    "ar_KW": "dd‏/MM‏/y",
    "ar_LB": "dd‏/MM‏/y",
    "ar_SA": "d MMM، y G",
    "bg_BG": "d.MM.y 'г'.",
    "en_BB": "d MMM y",
    "en_BM": "d MMM y",
    "en_GH": "d MMM y",
    "en_ID": "MMM d, y",
    "en_SG": "d MMM y",
    "es_BO": "d MMM 'de' y",
    "es_CL": "dd-MM-y",
    "es_CR": "d MMM y",
    "es_EC": "d MMM y",
    "es_GT": "d/MM/y",
    "es_HN": "d MMM y",
    "es_PE": "d MMM y",
    "es_PR": "MM/dd/y",
    "es_PY": "d MMM y",
    "es_SV": "d MMM y",
    "es_UY": "d MMM y",
    "et_EE": "d. MMM y",
    "fr_MC": "d MMM y",
    "hr_HR": "d. MMM y.",
    "hy_AM": "dd MMM, y թ.",
    "is_IS": "d. MMM y",
    "iw_IL": "d בMMM y",
    "kk_KZ": "y 'ж'. dd MMM",
    "km_KH": "d MMM y",
    "lt_LT": "y-MM-dd",
    "lv_LV": "y. 'gada' d. MMM",
    "ms_MY": "d MMM y",
    "nl_SR": "d MMM y",
    "pt_AO": "dd/MM/y",
    "ro_RO": "d MMM y",
    "sk_SK": "d. M. y",
    "sl_SI": "d. MMM y",
    "ur_PK": "y MMM d",
    "vi_VN": "d MMM, y",
    "in": "d MMM y",
    "ro": "d MMM y",
    "vi": "d MMM, y",
    "uk": "d MMM y 'р'.",
    "uk_UA": "d MMM y 'р'.",
    "ru_RU": "d MMM y 'г'.",
    "el": "d MMM y",
    "bg": "d.MM.y 'г'.",
    "es_DO": "d MMM y",
    "en_NG": "d MMM y",
    "ar_EG": "dd‏/MM‏/y",
    "es_PA": "MM/dd/y",
    "en_PH": "d MMM y",
    "tl": "MMM d, y",
    "tl_PH": "MMM d, y",
    "en_IN": "dd-MMM-y",
    "ka": "d MMM. y",
    "ka_GE": "d MMM. y",
    "sr": "dd.MM.y.",
    "sr_CS": "dd.MM.y.",
    "sr_BA": "dd.MM.y.",
    "sk": "d. M. y",
    "en_MY": "d MMM y",
    "sh": "dd.MM.y.",
    "sh_CS": "dd.MM.y.",
    "sh_BA": "dd.MM.y.",
    "bs": "d. MMM. y.",
    "bs_BA": "d. MMM. y.",
    "hr": "d. MMM y.",
    "sl": "d. MMM y",
    "ro_MD": "d MMM y",
    "mk": "dd.M.y",
    "mk_MK": "dd.M.y",
    "et": "d. MMM y",
    "lv": "y. 'gada' d. MMM",
    "lt": "y-MM-dd",
    "sq": "d MMM y",
    "sq_AL": "d MMM y",
    "eu": "y MMM d",
    "eu_ES": "y MMM d",
    "mt": "dd MMM y",
    "mt_MT": "dd MMM y",
    "ga": "d MMM y",
    "ga_IE": "d MMM y",
    "sh_ME": "dd.MM.y.",
    "is": "d. MMM y",
    "cy": "d MMM y",
    "cy_GB": "d MMM y",
    "az_AZ": "d MMM y",
    "ky_KG": "y-'ж'., d-MMM",
    "hi_IN": "dd/MM/y",
    "en_PK": "dd-MMM-y",
    "bn_BD": "d MMM, y",
    "ar_QA": "dd‏/MM‏/y",
    "be_BY": "d.MM.y",
    "tg_TJ": "MMM d, y",
    "ms": "d MMM y",
    "ms_BN": "d MMM y",
    "zh_MO": "y年M月d日",
    "zh_SG": "y年M月d日",
    "hy": "dd MMM, y թ.",
    "hi": "dd/MM/y",
    "rm": "dd-MM-y",
    "rm_CH": "dd-MM-y",
    "lb": "d. MMM y",
    "lb_LU": "d. MMM y",
    "ur": "y MMM d",
    "pl_PL": "d MMM y",
    "hu_HU": "y. MMM d.",
    "in_ID": "d MMM y",
    "tr_TR": "d MMM y",
    "zh_CN_STROKE": "y年M月d日",
    "zh_TW_STROKE": "y年M月d日",
    "zh_HK_STROKE": "y年M月d日",
    "zh_CN_PINYIN": "y年M月d日",
    "bn": "d MMM, y",
    "ta": "d MMM, y",
    "ta_IN": "d MMM, y",
    "ar_DZ": "dd‏/MM‏/y",
    "ar_IQ": "dd‏/MM‏/y",
    "ar_LY": "dd‏/MM‏/y",
    "ar_MA": "dd‏/MM‏/y",
    "ar_OM": "dd‏/MM‏/y",
    "ar_SD": "dd‏/MM‏/y",
    "ar_SY": "dd‏/MM‏/y",
    "ar_TN": "dd‏/MM‏/y",
    "ar_YE": "dd‏/MM‏/y",
    "en_HK": "d MMM y",
    "es_NI": "d MMM y",
    "es_US": "d MMM y",
    "eo": "y-MMM-dd",
    "eo_US": "y-MMM-dd",
    "iw_EO": "d בMMM y",
    "en_UG": "d MMM y",
    "en_KY": "d MMM y",
    "en_TT": "d MMM y",
    "ta_LK": "d MMM, y",
    "en_SH": "d MMM y",
    "so_DJ": "dd-MMM-y",
    "dz_BT": "སྤྱི་ལོ་y ཟླ་MMM ཚེས་dd",
    "fr_HT": "d MMM y",
    "en_SX": "d MMM y",
    "en_SL": "d MMM y",
    "en_SC": "d MMM y",
    "en_FK": "d MMM y",
    "en_MW": "d MMM y",
    "en_ER": "d MMM y",
    "en_PG": "d MMM y",
    "en_AG": "d MMM y",
    "en_GI": "d MMM y",
    "en_RW": "d MMM y",
    "fa_IR": "d MMM y",
    "en_BW": "dd MMM y",
    "en_BS": "d MMM y",
    "en_VU": "d MMM y",
    "ti_ET": "dd-MMM-y",
    "en_FJ": "d MMM y",
    "pt_ST": "dd/MM/y",
    "fr_WF": "d MMM y",
    "en_JM": "d MMM y",
    "en_MG": "d MMM y",
    "fr_MR": "d MMM y",
    "en_WS": "d MMM y",
    "rn_BI": "d MMM y",
    "fr_KM": "d MMM y",
    "fr_GN": "d MMM y",
    "en_SB": "d MMM y",
    "my_MM": "d MMM y",
    "pt_CV": "dd/MM/y",
    "en_KE": "d MMM y",
    "nl_AW": "d MMM y",
    "pt_MZ": "dd/MM/y",
    "yo_BJ": "d MMM y",
    "en_LR": "d MMM y",
    "en_MU": "d MMM y",
    "en_BZ": "dd-MMM-y",
    "lu_CD": "d MMM y",
    "es_CU": "d MMM y",
    "en_GM": "d MMM y",
    "en_CM": "d MMM y",
    "uz_LATN_UZ": "d-MMM, y",
    "en_GY": "d MMM y",
    "ps_AF": "G y MMM d",
    "ne_NP": "y MMM d",
    "en_NA": "d MMM y",
    "so_SO": "dd-MMM-y",
    "lo_LA": "d MMM y",
    "en_SZ": "d MMM y",
    "en_TO": "d MMM y",
    "en_TZ": "d MMM y",
    "ko_KP": "y. M. d.",
    "sr_RS": "dd.MM.y.",
    "de_BE": "dd.MM.y",
};